language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
before_script:
- "echo $JAVA_OPTS"
- "export JAVA_OPTS=-Xmx2048m"

script:
- mvn clean install -DskipTests=false -f ./dhis-2/pom-full.xml

cache:
  directories:
  - $HOME/.m2
  
branches:
  only:
  - master
  - /^2\.[0-9]{1,}/

notifications:
  slack:
    rooms:
      secure: SzjMaFPJ4TdfB5hqXFeXNT/8sTlzpiTcjGup6B3EJ2kqnGRGQaqusZMXWK7SvmVDbSYrTjNqoQQ9nLZMx1WrgDkamuJAoa1zxG7xHmUAptyk1taXPZo75MzQkHiM2JgUzZJ7G1S9G3W7sPuq2ocVwt5S1bBccPN5/InlkezZ8FleXDo5NIwPfp1EF4WEaHcBaQRxUCTfaHR1zL9B3MrmN0CbshS2iuO1Q/mk0zexSTKJe9VcNHuGlu1o71ImVEFkTHN8KVMONOJG8zhbKlpW02HtIqNUmJjIqHC+tNzGLPqhS4+MIiOkzyVldjZmcShfxodFLRA8F4pZgDzRVAYW8e4GfS+TKoccLcqGtPcoDl0rbtTzV/B0U2ibGBs5ZOW1n4lMaoXtGt7xQGlnavNKbz1e+1Y7AwP/0T3B8VE1wtPA9WGMl9niIXtwdRH+T1OSruK2S4SdTOnlsrVtykOqIlAYn5PRb3C2QU724TfCIZT/yWRdoVsnuFiamXuiDoYXUo3YfGpQZxZnNebUpfaXzf/0QaIajPWLiTKy/JiXvp5QaWLtbjf4qabMaOPKU26dQPxCD02CwP3GBlN5UxbsDcFmj1SxAVFarSW/a06hoMjEb5n5yitSOR5kUPFC2s0a4NJKTsvJSbiKHaVL23C8HWgiiQ5iaG+QcMxHOKiI3EI=
