DROP TABLE IF EXISTS _export_vcct;

CREATE TABLE _export_vcct AS
SELECT 
    tei,
    MAX(ouname)                      AS ouname,
    MAX("b1UJr0CT1bw")               AS uniquevcctid,
    MAX("ngtoqGYsc6M")               AS vcctid,
    MAX("x02F8oLroAi")               AS sitecode,
    MAX(CAST("EEjWFBzJKv8" AS date)) AS daReg,
    MAX("rQcCuLRLkIz")               AS PMRS,
    MAX("BluX3DCi6hh")               AS HTScode,
    MAX("e5FXJFKQyuB")               AS UUICcode,
    MAX("Lr70VXcNAc4")               AS IDpoor,
    MAX("BR1fUe7Nx8V")               AS sex,
    MAX(CAST("FmWxUZurqA8" AS date)) AS DaDob,
    MAX("Lj26NNuxm0k")               AS MaritalStatus,
    MAX("Fj2I8MsJ45D")               AS Occupation,
    MAX("Yd1LkEJ4nlp")               AS Occupation_other,
    MAX("YtPn9AL0lA4")               AS Education,
    MAX("Kd68BViw8AF")               AS Province,
    MAX("fW4E5W7ePjy")               AS District,
    MAX("f6ztgUdD9RV")               AS Commune,
    MAX("zUlWBlCUigl")               AS Village,
    MAX("Jq99T01JS6H")               AS PhoneNumber,
    MAX("hP0eFhT9Kbr")               AS Cob,
    MAX("xgUsvTfUR2L")               AS CobOther,
    MAX("myDjLmIpo5O")               AS ReferFrom,
    MAX("Ol87KVBKw8Z")               AS TPatient,
    MAX("d50l3rDtWPC")               AS HTest,
    MAX("w91DuzWoSxT")               AS HTestResult,
    MAX("PFVbvfaOYEb")               AS HPartnerresult1,
    MAX("vVKBBxtZF2r")               AS HPartnerresult2,
    MAX("GdsjfAiQprH")               AS AgreeTestHIV,
    MAX("bxLLR2XXI4J")               AS ComboResult,
    MAX("hY4TkdxNegd")               AS HIVResult,
    MAX("g1zPvFYsnru")               AS AgreeTestRTRI,
    MAX("JZRkmzKPEDv")               AS RTRIResult,
    MAX("fGmGxccnr68")               AS Firstinvalid,
    MAX("vuKwxoneL59")               AS AgreeTestVL,
    MAX("NR89IaUd4lN")               AS VLResult,
    MAX("a9cGaIinyOx")               AS RITAResult,
    MAX("bnetDTvv2Rx")               AS Counselor,
    MAX("t4rE0QPSIiA")               AS DaCounselor,
    MAX("ZPfgX1IUgeA")               AS TransferTo,
    MAX("Ltqnxpv5jMQ")               AS TransferToOther,
    MAX("KcCkkkw7Zd8")               AS NameCounselor,
    MAX(created)                     AS created,
    
    -- Clustered columns (C1–C18)
    MAX("jXoqL2Rz7rP")               AS C1,
    MAX("HYr7EkzwbMP")               AS C2,
    MAX("G5HsXuAn3ul")               AS C3,
    MAX("eMA0sIje4ek")               AS C4,
    MAX("Aef6lzbEX80")               AS C5,
    MAX("BCIo0Ys6TZo")               AS C6,
    MAX("VonwHNlhRei")               AS C7,
    MAX("VauYsPIUvt9")               AS C8,
    MAX("gOB7F5tBRQi")               AS C9,
    MAX("iJWF9mKSLj3")               AS C10,
    MAX("zHAFlHQyqk8")               AS C11,
    MAX("Ap7dkyL3tAz")               AS C12,
    MAX("IqoFEJPYMcT")               AS C13,
    MAX("SPKOmOEBXpa")               AS C14,
    MAX("EJdog3fceHm")               AS C15,
    MAX("B7usr8NS6Ki")               AS C16,
    MAX("p777d9jkvZd")               AS C17,
    MAX("p1ETBfYuKoF")               AS C18,

    -- Lab results
    MAX("SndD0MygBKZ")               AS Lcontrol,
    MAX("oIkL69IL356")               AS Lpositive,
    MAX("dsjiEqn066R")               AS LLongterm,
    MAX("xPjm6wcwmGX")               AS CamboAg,
    MAX("JhygTY337Kk")               AS CamboAb,

    -- Risk scores RS1–RS14
    MAX("PS6dCbhVf9c")               AS RS1,
    MAX("uWWEykCW1Uu")               AS RS2,
    MAX("a7Yyqoe25h9")               AS RS3,
    MAX("FWLZl5g30j4")               AS RS4,
    MAX("FJYRkWpH0cS")               AS RS5,
    MAX("HMeEPrJviJQ")               AS RS6,
    MAX("sS65gh0OMQT")               AS RS7,
    MAX("BUwznCiPVQx")               AS RS8,
    MAX("ArGt9rKGiLP")               AS RS9,
    MAX("WJfjlxfDqlJ")               AS RS10,
    MAX("ZwxjYyGiK15")               AS RS11,
    MAX("vC6IMPV5yle")               AS RS12,
    MAX("fRcDPtREvoo")               AS RS13,
    MAX("n0n9o3ExLM8")               AS RS14

FROM analytics_event_temp_d7ihumunaji
GROUP BY tei;
