// METADATA
export const METADATA_RECEIVED = 'METADATA_RECEIVED'
export const METADATA_ERRORED = 'METADATA_ERRORED'

// ORG UNIT
export const ORG_UNIT_SELECTED = 'ORG_UNIT_SELECTED'

// ALERT
export const ADD_ALERT = 'ADD_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

// DATA
export const RESET_DATA = 'RESET_DATA'
export const EXISTING_DATA_RECEIVED = 'EXISTING_DATA_RECEIVED'
export const EXISTING_DATA_ERRORED = 'EXISTING_DATA_ERRORED'
export const DISABLE_BUTTONS = 'DISABLE_BUTTONS'
export const ENABLE_BUTTONS = 'ENABLE_BUTTONS'
export const RESET_PANEL_EVENT = 'RESET_PANEL_EVENT'
export const SET_COMPLETED = 'SET_COMPLETED'
export const SET_INCOMPLETED = 'SET_INCOMPLETED'
export const SET_DELETE_PROMPT = 'SET_DELETE_PROMPT'
export const EXIT = 'EXIT'
export const SET_BUTTON_LOADING = 'SET_BUTTON_LOADING'


// ENTITY
export const SET_ENTITY = 'SET_ENTITY'
export const SET_ENTITY_VALUE = 'SET_ENTITY_VALUE'
export const SET_UNIQUE = 'SET_UNIQUE'
export const SET_ENTITY_MODAL_AND_UNIQUES = 'SET_ENTITY_MODAL_AND_UNIQUES'
export const SET_EDITING = 'SET_EDITING'
export const SET_MODAL_LOADING = 'SET_MODAL_LOADING'

// PANEL
export const SET_PANEL = 'SET_PANEL'
export const SET_PANEL_VALUE = 'SET_PANEL_VALUE'
export const RESET_PANEL = 'RESET_PANEL'

// EVENT
export const SET_ENTITY_AND_ORG_UNIT = 'SET_ENTITY_AND_ORG_UNIT'
export const SET_EVENT_VALUE = 'SET_EVENT_VALUE'
export const SET_EVENT_AND_ENTITY = 'SET_EVENT_AND_ENTITY'
export const SET_EVENT_VALUES_AND_PROGRAMSTAGE =
    'SET_EVENT_VALUES_AND_PROGRAMSTAGE'
export const DUPLICACY = 'DUPLICACY'
export const NEW_EVENT_ERRORED = 'NEW_EVENT_ERRORED'

// added by for tanda
export const SET_PREVIOUS_ENTITY = "SET_PREVIOUS_ENTITY"
export const RESET_PREVIOUS_ENTITY = "RESET_PREVIOUS_ENTITY"
export const ADD_ENTITY = "ADD_ENTITY"
export const PANEL_EDITABLE = "PANEL_EDITABLE"
export const EXISTING_TEI_DATA_RECEIVED = "EXISTING_TEI_DATA_RECEIVED"
export const REMOVE_BUTTONS = "REMOVE_BUTTONS"
export const SET_PREVIOUS_EVENT = "SET_PREVIOUS_EVENT"
export const SET_EVENT = "SET_EVENT"
// export const SET_PREVALUE = "SET_PREVALUE"
export const PAGE_FIRST = "PAGE_FIRST"
export const COMPLETED_CLICKED = 'COMPLETED_CLICKED'
export const RESET_SAMPLE_PANEL_EVENT = 'RESET_SAMPLE_PANEL_EVENT'
export const MARKED_FOLLOW  = 'MARKED_FOLLOW'

//Added for aggregation progress
export const AGGREGATION_ON_PROGRESS = 'AGGREGATION_ON_PROGRESS'







